# Generated by Django 2.2.5 on 2019-09-17 14:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField(default=datetime.datetime(2019, 9, 17, 14, 47, 27, 826782, tzinfo=utc), help_text='Enter the publication date of the article.', verbose_name='publish date')),
                ('like', models.SmallIntegerField(default=0, verbose_name='you like it')),
                ('dislike', models.SmallIntegerField(default=0, verbose_name='you dislike it')),
                ('title', models.CharField(help_text='Enter title.', max_length=300, verbose_name='title')),
                ('entry', models.TextField(help_text='Your blog entry', verbose_name='blog entry')),
                ('for_adult', models.BooleanField(default=False, verbose_name='adult content')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'article',
                'verbose_name_plural': 'articles',
            },
        ),
    ]
