# Generated by Django 2.2.5 on 2019-09-17 14:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog_entries', '0002_auto_20190917_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Enter the publication date of the article.', verbose_name='publish date'),
        ),
    ]
