# Generated by Django 2.2.5 on 2019-09-17 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog_entries', '0003_auto_20190917_1650'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['pub_date'], 'verbose_name': 'article', 'verbose_name_plural': 'articles'},
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField(default=django.utils.timezone.now, help_text='Enter the publication date of the article.', verbose_name='publish date')),
                ('content_comment', models.CharField(help_text='Comment for entry blog.', max_length=500, verbose_name='comment')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_entries.Article')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
                'ordering': ['pub_date'],
            },
        ),
    ]
