# Generated by Django 2.2.5 on 2019-09-19 11:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_entries', '0005_auto_20190917_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='entry',
            field=models.TextField(help_text='Your blog entry', validators=[django.core.validators.MinLengthValidator(limit_value=300)], verbose_name='blog entry'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(help_text='Enter title.', max_length=300, validators=[django.core.validators.MinLengthValidator(limit_value=10)], verbose_name='title'),
        ),
    ]
