# Generated by Django 2.2.5 on 2019-09-19 11:52

import blog_entries.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_entries', '0007_auto_20190919_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='entry',
            field=models.TextField(help_text='Your blog entry', validators=[django.core.validators.MinLengthValidator(limit_value=200), blog_entries.validators.check_is_digit_validator], verbose_name='blog entry'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(help_text='Enter title.', max_length=300, validators=[django.core.validators.MinLengthValidator(limit_value=10), blog_entries.validators.check_is_digit_validator], verbose_name='title'),
        ),
    ]
