# Generated by Django 2.2.5 on 2019-09-19 12:38

import blog_entries.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_entries', '0008_auto_20190919_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog_entries.Article'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content_comment',
            field=models.CharField(help_text='Comment for entry blog.', max_length=400, validators=[django.core.validators.MinLengthValidator(limit_value=10), blog_entries.validators.check_is_digit_validator], verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
