# Generated by Django 2.2.5 on 2019-09-19 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_entries', '0009_auto_20190919_1438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-pub_date'], 'verbose_name': 'article', 'verbose_name_plural': 'articles'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-pub_date'], 'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
    ]
