# Generated by Django 2.2.5 on 2019-09-17 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogprofile',
            options={'verbose_name': 'blogprofile', 'verbose_name_plural': 'blogprofiles'},
        ),
    ]
